# Generated by Django 5.0.2 on 2024-04-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='Oops'),
        ),
    ]
