# Generated by Django 5.0.2 on 2024-04-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0003_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(),
        ),
    ]
