# Generated by Django 5.0.3 on 2024-03-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='password',
        ),
    ]
