# Generated by Django 5.0.2 on 2024-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
