# Generated by Django 5.0.7 on 2024-07-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_invitelink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
